### PR TITLE
Switch llvm::Argument processing to use iterators

### LINKED ISSUE #136: Build on OS X is broken
```
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/GasMeter.cpp:169:22: error: no member named 'getNextNode' in 'llvm::Argument'
        auto cost = gasPtr->getNextNode();
                    ~~~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Ext.cpp:67:13: error: no matching member function for call to 'SetInsertPoint'
                m_builder.SetInsertPoint(allocaIt);
                ~~~~~~~~~~^~~~~~~~~~~~~~
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:91:8: note: candidate function not viable: no known conversion from 'llvm::ilist_iterator<llvm::Instruction>' to 'llvm::BasicBlock *' for 1st argument
  void SetInsertPoint(BasicBlock *TheBB) {
       ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:98:8: note: candidate function not viable: no known conversion from 'llvm::ilist_iterator<llvm::Instruction>' to 'llvm::Instruction *' for 1st argument
  void SetInsertPoint(Instruction *I) {
       ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:107:8: note: candidate function not viable: requires 2 arguments, but 1 was provided
  void SetInsertPoint(BasicBlock *TheBB, BasicBlock::iterator IP) {
       ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Array.cpp:37:25: error: no member named 'getNextNode' in 'llvm::Argument'
        auto value = arrayPtr->getNextNode();
                     ~~~~~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Array.cpp:87:25: error: no member named 'getNextNode' in 'llvm::Argument'
        auto index = arrayPtr->getNextNode();
                     ~~~~~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Array.cpp:111:25: error: no member named 'getNextNode' in 'llvm::Argument'
        auto index = arrayPtr->getNextNode();
                     ~~~~~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Array.cpp:133:25: error: no member named 'getNextNode' in 'llvm::Argument'
        auto index = arrayPtr->getNextNode();
                     ~~~~~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Array.cpp:191:27: error: no member named 'getNextNode' in 'llvm::Argument'
        auto newSize = arrayPtr->getNextNode();
                       ~~~~~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:86:14: error: no member named 'getNextNode' in 'llvm::Argument'
        auto y = x->getNextNode();
                 ~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/BasicBlock.cpp:170:23: error: no member named 'getNextNode' in 'llvm::Argument'
        auto sizePtr = base->getNextNode();
                       ~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:203:17: error: no member named 'getNextNode' in 'llvm::Argument'
        auto yArg = x->getNextNode();
                    ~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:301:14: error: no member named 'getNextNode' in 'llvm::Argument'
        auto y = x->getNextNode();
                 ~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:325:14: error: no member named 'getNextNode' in 'llvm::Argument'
        auto y = x->getNextNode();
                 ~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:369:14: error: no member named 'getNextNode' in 'llvm::Argument'
        auto y = x->getNextNode();
                 ~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:415:14: error: no member named 'getNextNode' in 'llvm::Argument'
        auto y = x->getNextNode();
                 ~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:441:14: error: no member named 'getNextNode' in 'llvm::Argument'
        auto y = x->getNextNode();
                 ~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Arith256.cpp:464:25: error: no member named 'getNextNode' in 'llvm::Argument'
                auto exponent = base->getNextNode();
                                ~~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Compiler.cpp:117:4: error: no matching constructor for initialization of 'IRBuilder' (aka 'IRBuilder<>')
                        IRBuilder{it}.CreateBr(nextBlock);
                        ^        ~~~~
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:540:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'llvm::ilist_iterator<llvm::BasicBlock>' to 'const llvm::IRBuilder<true, llvm::ConstantFolder,
      llvm::IRBuilderDefaultInserter<true> >' for 1st argument
class IRBuilder : public IRBuilderBase, public Inserter {
      ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:540:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'llvm::ilist_iterator<llvm::BasicBlock>' to
      'llvm::IRBuilder<true, llvm::ConstantFolder, llvm::IRBuilderDefaultInserter<true> >' for 1st argument
class IRBuilder : public IRBuilderBase, public Inserter {
      ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:550:12: note: candidate constructor not viable: no known conversion from 'llvm::ilist_iterator<llvm::BasicBlock>' to 'llvm::LLVMContext &' for 1st argument
  explicit IRBuilder(LLVMContext &C, MDNode *FPMathTag = nullptr,
           ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:560:12: note: candidate constructor not viable: no known conversion from 'llvm::ilist_iterator<llvm::BasicBlock>' to 'llvm::BasicBlock *' for 1st argument
  explicit IRBuilder(BasicBlock *TheBB, MDNode *FPMathTag = nullptr,
           ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:566:12: note: candidate constructor not viable: no known conversion from 'llvm::ilist_iterator<llvm::BasicBlock>' to 'llvm::Instruction *' for 1st argument
  explicit IRBuilder(Instruction *IP, MDNode *FPMathTag = nullptr,
           ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:554:12: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
  explicit IRBuilder(BasicBlock *TheBB, const T &F, MDNode *FPMathTag = nullptr,
           ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:579:3: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
  IRBuilder(BasicBlock *TheBB, BasicBlock::iterator IP,
  ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:544:3: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
  IRBuilder(LLVMContext &C, const T &F, Inserter I = Inserter(),
  ^
/usr/local/opt/llvm/include/llvm/IR/IRBuilder.h:572:3: note: candidate constructor not viable: requires at least 3 arguments, but 1 was provided
  IRBuilder(BasicBlock *TheBB, BasicBlock::iterator IP, const T &F,
  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Compiler.cpp:128:42: error: no viable conversion from 'llvm::ilist_iterator<llvm::BasicBlock>' to 'llvm::BasicBlock *'
                                jumpTableInput->addIncoming(destIdx, it); // Fill up PHI node
                                                                     ^~
/usr/local/opt/llvm/include/llvm/IR/Instructions.h:2569:42: note: passing argument to parameter 'BB' here
  void addIncoming(Value *V, BasicBlock *BB) {
                                         ^
1 error generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/GasMeter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 24%] Building CXX object libethcore/CMakeFiles/ethcore.dir/ChainOperationParams.cpp.o
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Memory.cpp:36:25: error: no member named 'getNextNode' in 'llvm::Argument'
                auto blkOffset = mem->getNextNode();
                                 ~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Memory.cpp:110:20: error: no member named 'getNextNode' in 'llvm::Argument'
        auto index = mem->getNextNode();
                     ~~~  ^
/Users/aeufemio/projects/ethereum/webthree-umbrella/solidity/libethereum/evmjit/libevmjit/Optimizer.cpp:60:35: error: no viable conversion from 'llvm::ilist_iterator<llvm::BasicBlock>' to 'llvm::BasicBlock *'
                        retPhi->addIncoming(abortCode, bbIt);
                                                       ^~~~
/usr/local/opt/llvm/include/llvm/IR/Instructions.h:2569:42: note: passing argument to parameter 'BB' here
  void addIncoming(Value *V, BasicBlock *BB) {
                                         ^
1 error generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/BasicBlock.cpp.o] Error 1
[ 24%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Common.cpp.o
8 errors generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/Arith256.cpp.o] Error 1
[ 25%] Building CXX object libethcore/CMakeFiles/ethcore.dir/CommonJS.cpp.o
[ 26%] Building CXX object libethcore/CMakeFiles/ethcore.dir/ICAP.cpp.o
1 error generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/Optimizer.cpp.o] Error 1
[ 27%] Building CXX object libethcore/CMakeFiles/ethcore.dir/KeyManager.cpp.o
[ 28%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Precompiled.cpp.o
1 error generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/Ext.cpp.o] Error 1
[ 29%] Building CXX object libethcore/CMakeFiles/ethcore.dir/SealEngine.cpp.o
5 errors generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/Array.cpp.o] Error 1
[ 29%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Transaction.cpp.o
2 errors generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/Compiler.cpp.o] Error 1
2 errors generated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/Memory.cpp.o] Error 1
make[1]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 30%] Linking CXX shared library libevmcore.dylib
[ 30%] Built target evmcore
[ 31%] Linking CXX shared library libethcore.dylib
[ 31%] Built target ethcore
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by bobsummerwill**
Work-in-progress on switching processing of llvm::Argument elements (mainly from llvm::Function) to use iterators, rather than getNextNode(), to address build breaks against LLVM HEAD (work towards 3.9).

These changes should work with older LLVM versions too (such as 3.7.1, the current stable version).

Seeking to resolve https://github.com/ethereum/webthree-umbrella/issues/136

Still needs finishing up and review and squashing.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
FYI ... @chfast.

File: evmjit/libevmjit/Arith256.cpp [hunk 1]
```diff
@@ -81,10 +81,12 @@ llvm::Function* generateLongMulFunc(char const* _funcName, llvm::IntegerType* _t
 	func->setDoesNotAccessMemory();
 	func->setDoesNotThrow();
 
-	auto x = &func->getArgumentList().front();
-	x->setName("x");
-	auto y = x->getNextNode();
-	y->setName("y");
+	auto iter = func->getArgumentList().begin();
+	llvm::Argument& x = (*iter++);
```
Comment (chriseth) [inline evmjit/libevmjit/Arith256.cpp]: If you want to use parentheses, I would find `*(iter++)` more readable, and the parentheses below can be dropped, I think.

**Comment by chriseth** [comment]
On a side note: Do I see that right that `MUL` and `DIV` are converted into function calls? If yes, are they inlined during optimization so that contextual information (factors are all smaller than 2**32, one factor is 1, one factor is 0, ...) can be taken into account?

File: evmjit/libevmjit/Arith256.cpp (hunk 1 above)
Comment (chfast) [inline evmjit/libevmjit/Arith256.cpp]: You forgot setting names for arguments.

Comment (chfast) [inline evmjit/libevmjit/Arith256.cpp]: Keep `x` and `y` as pointer. LLVM API is designed this way. You will avoid many unnecessary changes later.

File: evmjit/libevmjit/Compiler.cpp [hunk 2]
```diff
@@ -109,12 +109,14 @@ void Compiler::resolveJumps()
...
-		auto nextBlock = it->getNextNode(); // If the last code block, that will be "stop" block.
+		auto nextBlockIter = it;
+		++nextBlockIter; // If the last code block, that will be "stop" block.
+		
 		auto term = it->getTerminator();
 		llvm::BranchInst* jump = nullptr;
 
 		if (!term) // Block may have no terminator if the next instruction is a jump destination.
-			IRBuilder{it}.CreateBr(nextBlock);
+			IRBuilder{&(*it)}.CreateBr(&(*nextBlockIter));
```
Comment (chfast) [inline evmjit/libevmjit/Compiler.cpp]: WTF is going on here?

File: evmjit/libevmjit/GasMeter.cpp [hunk 3]
```diff
@@ -164,26 +164,28 @@ GasMeter::GasMeter(IRBuilder& _builder, RuntimeManager& _runtimeManager) :
 	auto updateBB = llvm::BasicBlock::Create(_builder.getContext(), "Update", m_gasCheckFunc);
 	auto outOfGasBB = llvm::BasicBlock::Create(_builder.getContext(), "OutOfGas", m_gasCheckFunc);
 
-	auto gasPtr = &m_gasCheckFunc->getArgumentList().front();
-	gasPtr->setName("gasPtr");
-	auto cost = gasPtr->getNextNode();
-	cost->setName("cost");
-	auto jmpBuf = cost->getNextNode();
-	jmpBuf->setName("jmpBuf");
+	auto iter = m_gasCheckFunc->getArgumentList().begin();
```
Comment (chfast) [inline evmjit/libevmjit/GasMeter.cpp]: This can be simplified as `m_gasCheckFunc->arg_begin()`.

File: evmjit/libevmjit/GasMeter.cpp [hunk 4]
```diff
@@ -164,26 +164,28 @@ GasMeter::GasMeter(IRBuilder& _builder, RuntimeManager& _runtimeManager) :
...
+	llvm::Argument& gasPtr = (*iter++);
```
Comment (chfast) [inline evmjit/libevmjit/GasMeter.cpp]: Keep them as pointers: `llvm::Argument* gasPtr = iter++;`. Magic, I know.

**Comment by chfast** [comment]
@chriseth `mul` is replaced with a function _after_ optimizations applied.

**Comment by chriseth** [comment]
@chfast ah, interesting, thanks!

**Comment by bobsummerwill** [comment]
See http://llvm.org/docs/ProgrammersManual.html#basic-inspection-and-traversal-routines.

Yeah - pretty odd semantics, eh!

Just in the process reworking it all to minimize the diffs while keeping the "actually builds for me" :-)   And will then squash.

**Comment by bobsummerwill** [comment]
OK, guys.    I think this PR is ready to go now.
I've reworked it all again, for minimal impact.    It appears that those implicit conversions have been removed from LLVM HEAD (rightly, because they were very weird), so what I've ended up with uses conventional iterator syntax and semantics.   Pretty ugly to have to de-reference the iterators, and then do address-of on them to get the pointers, but I've made it as clear as I can.

File: evmjit/libevmjit/Compiler.cpp (hunk 2 above)
Comment (bobsummerwill) [inline evmjit/libevmjit/Compiler.cpp]: I know!   Beautiful, eh?   Clearer in the latest code, but the {} brackets really don't help.

File: evmjit/libevmjit/GasMeter.cpp (hunk 3 above)
Comment (bobsummerwill) [inline evmjit/libevmjit/GasMeter.cpp]: Thanks for that tip.   Done everywhere.

**Comment by bobsummerwill** [comment]
Hmm ... So I rebased and am not sure when the automation ran.
Is there a way for us to force it to run again, to verify that these tests ARE actually failing.
What is the best way for us to troubleshoot test failures?   We don't have a continuously running automation post-check-in, do we?

**Comment by chriseth** [comment]
You can verify which commit the CI ran against by checking the icon next to the commit has on the right side here on this screen. There were 4 failures all which are unrelated and known.
If you want to re-run, you can amend your last commit (without any changes apart from the timestamp) and force-push. The CI will automatically pick up new or changed commits in a PR.
